### ISSUE TITLE
Bug Report: Uncommon link form

### ISSUE THREAD

**Issue by ysl970629** [mathiassoeholm/markdown-link-updater#1]
> At first, I want to express my sincere thanks to you beacuse this plugin helped me a lot. I am not a native English speaker, all the words are translated by google translate. So if my tone offends you, I will apologize to you. 

When I migrated all the notes to other software, I found that all the internal links to the documents were broken. In the end, I found out that the plugin changed the link form and was not universal enough, which caused other note-taking software to fail to recognize it.

The internal link format followed by this plugin is as follows:

```
[a_link](folder1\folder2\file.md)
```

![image](https://user-images.githubusercontent.com/39717545/100097659-d0072280-2e97-11eb-8eaa-02b27eaf03a1.png)

In VSCode and Typora, this is allowed. But in other softwere (e.g. Obsidian and Github), this link can't be recognized as an internal link. A link that could be identified well by most softwere like this:

```
[a_link](./folder1/folder2/file.md)
```

In my humble opinion, `./` and `/` are the important parts, and I was wondering if you could provide a setting for users to select a kind of form they needed, and these forms could be converted easily.

Test Environment:

Windows 10 version 1909 (Maybe this bug is only occured in Windows platform ? I'm not sure)
Plugin version v1.1.1

**Comment by mathiassoeholm** [comment]
I would never guess that your message was translated by Google Translate, that's amazing actually.
I'm super happy to hear that you find the plugin useful :-)

I think the problem is because of the backslashes. At least GitHub works fine without the `.`, but I'm not sure about Obsidian.

Even though Windows uses backslash, I think the correct thing to do in Markdown files is to convert them to regular slashes for portability. I have done that in version `1.1.2`.

Can you try updating and see if it works?

**Comment by ysl970629** [comment]
> I would never guess that your message was translated by Google Translate, that's amazing actually.
> I'm super happy to hear that you find the plugin useful :-)
> 
> I think the problem is because of the backslashes. At least GitHub works fine without the `.`, but I'm not sure about Obsidian.
> 
> Even though Windows uses backslash, I think the correct thing to do in Markdown files is to convert them to regular slashes for portability. I have done that in version `1.1.2`.
> 
> Can you try updating and see if it works?

I have tried v1.1.2, it works well with links `[]()`, but for images `![]()`, it still doesn't work. @mathiassoeholm

**Comment by mathiassoeholm** [comment]
That makes sense. I forgot that there are two places where I'm updating links. First in the file(s) being renamed and second in the file(s) linking to this file.

I have added the necessary change in 1.1.3. I can't reproduce this issue myself because I'm on a Mac, but will you do me the favour again of testing it? :-)

**Comment by ysl970629** [comment]
Everything is working fine now.

Thank you very much, This plugin has helped me a lot because I always take notes in VSCode, and refactoring is a very important part of it. I will recommend this plugin to my friends as much as possible.
